package org.shda;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Environment;
import android.widget.Toast;
import androidx.core.content.FileProvider;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class PdfReportService {
    
    private static final DeviceRgb SAFFRON = new DeviceRgb(230, 81, 0);
    private static final DeviceRgb BLUE = new DeviceRgb(25, 118, 210);
    private static final DeviceRgb GREEN = new DeviceRgb(46, 125, 50);
    private static final DeviceRgb RED = new DeviceRgb(211, 47, 47);
    private static final DeviceRgb GREY_BG = new DeviceRgb(240, 240, 240);

    private static String getFormattedFileName(String communityName, String reportType) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmm", Locale.getDefault());
        String safeCommunity = communityName.replaceAll("[^a-zA-Z0-9]", "");
        String safeReport = reportType.replaceAll("[^a-zA-Z0-9]", "_");
        return safeCommunity + "_" + safeReport + "_" + sdf.format(new Date()) + ".pdf";
    }

    private static void addSanataniHeader(Context context, Document document, String communityName, String reportType) {
        document.add(new Paragraph(communityName.toUpperCase())
                .setFontColor(SAFFRON).setBold().setFontSize(24).setTextAlignment(TextAlignment.CENTER));
        document.add(new Paragraph(ShlokaEngine.getPdfSafeShloka(context))
                .setFontSize(11).setItalic().setFontColor(new DeviceRgb(117, 117, 117)).setTextAlignment(TextAlignment.CENTER));
        document.add(new Paragraph(reportType)
                .setBold().setFontSize(14).setBackgroundColor(GREY_BG).setTextAlignment(TextAlignment.CENTER).setMarginTop(8f).setPadding(4f));
        document.add(new Paragraph("Generated: " + new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(new Date()))
                .setFontSize(10).setItalic().setTextAlignment(TextAlignment.CENTER).setMarginBottom(15f));
    }

    private static void addFooterSignature(Document document, String generatedBy) {
        document.add(new Paragraph("\nAuthorized & Generated By: " + generatedBy)
                .setFontSize(9).setItalic().setFontColor(new DeviceRgb(150, 150, 150)).setTextAlignment(TextAlignment.RIGHT).setMarginTop(20f));
    }

    // 1. LOGIN CREDENTIALS
    public static void generateLoginCredentialsPdf(Context context, String communityName, String memberName, String memberId, String password, String role) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
            File file = new File(path, getFormattedFileName(communityName, memberId + "_Credentials"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));

            addSanataniHeader(context, document, communityName, "CONFIDENTIAL: ACCESS CREDENTIALS");
            
            document.add(new Paragraph("Welcome to the digital portal of " + communityName + "!").setBold().setFontSize(14).setTextAlignment(TextAlignment.CENTER));
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2})).useAllAvailableWidth().setMarginTop(15f);
            table.addCell(new Cell().add(new Paragraph("Name").setBold()));
            table.addCell(new Cell().add(new Paragraph(memberName)));
            table.addCell(new Cell().add(new Paragraph("Assigned Role").setBold()));
            table.addCell(new Cell().add(new Paragraph(role).setFontColor(BLUE)));
            table.addCell(new Cell().add(new Paragraph("SB-ID (Login ID)").setBold()));
            table.addCell(new Cell().add(new Paragraph(memberId).setBold().setFontColor(SAFFRON)));
            table.addCell(new Cell().add(new Paragraph("Secure PIN").setBold()));
            table.addCell(new Cell().add(new Paragraph(password).setBold().setFontColor(RED)));
            document.add(table);

            document.add(new Paragraph("\n* Important: Please keep this document secure. Do not share your PIN with anyone.")
                .setItalic().setFontSize(10).setFontColor(new DeviceRgb(97, 97, 97)).setMarginTop(10f));

            document.close(); shareFile(context, file, memberName + " - Login Credentials");
        } catch (Exception e) {}
    }

    // 2. FINANCIAL / INCOME REPORT
    public static void generateFinancialReport(Context context, String communityName, List<String> dates, List<String> names, List<Float> amounts, List<String> notes, float totalDonations, String reportRange) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Income_Statement"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL INCOME STATEMENT");
            document.add(new Paragraph(reportRange).setFontSize(11).setTextAlignment(TextAlignment.CENTER).setMarginBottom(10f));
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{2, 3, 3, 2})).useAllAvailableWidth();
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Date").setBold()));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Donor Name").setBold()));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Purpose/Note").setBold()));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Amount (৳)").setBold().setTextAlignment(TextAlignment.RIGHT)));

            if (names.isEmpty()) { 
                table.addCell(new Cell(1, 4).add(new Paragraph("No transactions recorded.").setItalic().setTextAlignment(TextAlignment.CENTER))); 
            } else {
                for(int i = 0; i < names.size(); i++) {
                    table.addCell(new Cell().add(new Paragraph(dates.get(i)).setFontSize(10)));
                    table.addCell(new Cell().add(new Paragraph(names.get(i)).setFontSize(10)));
                    table.addCell(new Cell().add(new Paragraph(notes.get(i)).setFontSize(10)));
                    table.addCell(new Cell().add(new Paragraph(String.valueOf(amounts.get(i))).setFontSize(10).setTextAlignment(TextAlignment.RIGHT)));
                }
            }
            document.add(table);

            document.add(new Paragraph("Total Collected: ৳" + totalDonations)
                    .setBold().setFontSize(14).setFontColor(GREEN).setTextAlignment(TextAlignment.RIGHT).setMarginTop(10f));
            
            document.close(); shareFile(context, file, communityName + " - Income Report");
        } catch (Exception e) {}
    }

    // 3. DONOR RECEIPT
    public static void generateDonorReceipt(Context context, String communityName, String name, float amount, String note, String date) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Chanda_Receipt"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL CHANDA RECEIPT");
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2})).useAllAvailableWidth().setMarginTop(20f);
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Transaction Date").setBold()));
            table.addCell(new Cell().add(new Paragraph(date)));
            
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Received From").setBold()));
            table.addCell(new Cell().add(new Paragraph(name).setBold().setFontSize(14).setFontColor(SAFFRON)));
            
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Contribution Amount").setBold()));
            table.addCell(new Cell().add(new Paragraph("৳" + amount).setBold().setFontSize(14).setFontColor(GREEN)));
            
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Purpose/Note").setBold()));
            table.addCell(new Cell().add(new Paragraph(note.isEmpty() ? "General Donation" : note)));
            document.add(table);

            document.add(new Paragraph("\nMay Ishvara shower you with infinite blessings.").setItalic().setFontSize(12).setTextAlignment(TextAlignment.CENTER).setMarginTop(20f));
            
            document.close(); shareFile(context, file, communityName + " - Receipt");
        } catch (Exception e) {}
    }

    // 4. DONOR STATEMENT (LIFETIME)
    public static void generateDonorStatement(Context context, String communityName, TransactionActivity.GroupedDonation gd) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            String safeName = gd.displayName.replace("[Member]", "").replace("[Guest]", "").trim();
            File file = new File(path, getFormattedFileName(communityName, safeName + "_Statement"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "LIFETIME DONOR STATEMENT");
            
            document.add(new Paragraph("Donor: " + gd.displayName).setBold().setFontSize(16).setFontColor(SAFFRON).setTextAlignment(TextAlignment.CENTER));
            document.add(new Paragraph("Lifetime Contribution: ৳" + gd.totalDonated).setBold().setFontSize(14).setFontColor(GREEN).setTextAlignment(TextAlignment.CENTER).setMarginBottom(15f));
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{3, 4, 3, 2})).useAllAvailableWidth();
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Date").setBold().setFontSize(11)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Note/Purpose").setBold().setFontSize(11)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Handled By").setBold().setFontSize(11)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Amount").setBold().setFontSize(11).setTextAlignment(TextAlignment.RIGHT)));

            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault());
            gd.history.sort((a, b) -> Long.compare(b.timestamp, a.timestamp));

            for(TransactionActivity.SingleDonation sd : gd.history) {
                table.addCell(new Cell().add(new Paragraph(sdf.format(new Date(sd.timestamp))).setFontSize(10)));
                table.addCell(new Cell().add(new Paragraph(sd.note).setFontSize(10)));
                table.addCell(new Cell().add(new Paragraph(sd.collectedBy != null ? sd.collectedBy : "System").setFontSize(10)));
                table.addCell(new Cell().add(new Paragraph("৳" + sd.amount).setFontSize(10).setTextAlignment(TextAlignment.RIGHT)));
            }
            document.add(table);
            document.close(); shareFile(context, file, gd.displayName + " Statement");
        } catch (Exception e) {}
    }

    // 5. MEMBER DIRECTORY
    public static void generateMemberDirectory(Context context, String communityName, List<Member> memberList) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Member_Directory"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL MEMBER DIRECTORY");
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{2, 3, 3, 2, 2})).useAllAvailableWidth();
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("SB-ID").setBold().setFontSize(10)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Name").setBold().setFontSize(10)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Phone").setBold().setFontSize(10)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Role").setBold().setFontSize(10)));
            table.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Donated (৳)").setBold().setFontSize(10).setTextAlignment(TextAlignment.RIGHT)));

            for (Member m : memberList) {
                table.addCell(new Cell().add(new Paragraph(m.id).setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(m.name).setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(m.phone != null ? m.phone : "N/A").setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(m.role != null ? m.role : "MEMBER").setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(m.totalDonated)).setFontSize(9).setTextAlignment(TextAlignment.RIGHT)));
            }
            document.add(table);
            document.close(); shareFile(context, file, communityName + " Directory");
        } catch (Exception e) {}
    }

    // 6. MEMBER PROFILE
    public static void generateMemberProfile(Context context, String communityName, Member member) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, member.id + "_Profile"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL DEVOTEE RECORD");

            Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2})).useAllAvailableWidth().setMarginTop(15f);

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Devotee Name").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.name).setBold().setFontSize(12)));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("SB-ID (System ID)").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.id).setFontColor(BLUE)));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Phone Number").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.phone != null ? member.phone : "N/A")));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Gotra").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.gotra != null && !member.gotra.isEmpty() ? member.gotra : "N/A")));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Blood Group").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.bloodGroup != null && !member.bloodGroup.isEmpty() ? member.bloodGroup : "N/A").setFontColor(RED)));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Address").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.address != null && !member.address.isEmpty() ? member.address : "N/A")));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Lifetime Donated").setBold()));
            table.addCell(new Cell().add(new Paragraph("৳" + member.totalDonated).setBold().setFontColor(GREEN)));

            document.add(table);
            document.add(new Paragraph("\nData Verified By: " + (member.addedBySignature != null ? member.addedBySignature : "System")).setItalic().setFontSize(9));
            document.close(); shareFile(context, file, member.name + " Profile");
        } catch (Exception e) {}
    }

    // 7. EVENT ITINERARY
    public static void generateEventItinerary(Context context, String communityName, EventActivity.Event event, String generatedBy) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Event_Itinerary"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL MANDIR EVENT ITINERARY");
            document.add(new Paragraph(event.title).setBold().setFontSize(18).setFontColor(SAFFRON).setTextAlignment(TextAlignment.CENTER));
            
            Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2})).useAllAvailableWidth().setMarginTop(15f);
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Date & Time").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.dateStr + " at " + event.timeStr)));
            
            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Location").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.location)));

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Description").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.description)));

            if (event.adminComment != null && !event.adminComment.trim().isEmpty()) {
                table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Management Note").setBold()));
                table.addCell(new Cell().add(new Paragraph(event.adminComment).setItalic()));
            }

            table.addCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Push Alerts Sent").setBold()));
            table.addCell(new Cell().add(new Paragraph(String.valueOf(event.notificationCount))));

            document.add(table);
            document.add(new Paragraph("\nEvent Scheduled By: " + event.createdBy).setItalic().setFontSize(10).setFontColor(new DeviceRgb(117, 117, 117)));
            addFooterSignature(document, generatedBy);
            
            document.close(); shareFile(context, file, event.title + " Itinerary");
        } catch (Exception e) {}
    }

    // 8. SECURITY AUDIT
    public static class AuditEntry {
        public String date, user, action, details, role;
        public AuditEntry(String d, String u, String a, String det, String r) { date=d; user=u; action=a; details=det; role=r; }
    }

    public static void generateBeautifulAuditReport(Context context, String communityName, List<AuditEntry> logs, String reportRange) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Security_Audit"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "SECURITY AUDIT & ACTIVITY LOG");
            document.add(new Paragraph(reportRange).setFontSize(12).setTextAlignment(TextAlignment.CENTER).setMarginBottom(15f));
            
            if (logs.isEmpty()) { 
                document.add(new Paragraph("No activity recorded for this period.").setTextAlignment(TextAlignment.CENTER)); 
            } else {
                List<AuditEntry> adminLogs = new ArrayList<>(); List<AuditEntry> managerLogs = new ArrayList<>();
                for (AuditEntry log : logs) {
                    if ("ADMIN".equals(log.role)) adminLogs.add(log); else managerLogs.add(log);
                }

                // 🟥 SUPER ADMIN SECTION
                document.add(new Paragraph("🛡️ SUPER ADMIN ACTIVITY").setBold().setFontSize(14).setFontColor(SAFFRON).setBackgroundColor(new DeviceRgb(255, 243, 224)).setPadding(4f));
                Table adminTable = new Table(UnitValue.createPercentArray(new float[]{2, 2, 4})).useAllAvailableWidth().setMarginBottom(15f);
                adminTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Date").setBold().setFontSize(10)));
                adminTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("User").setBold().setFontSize(10)));
                adminTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Action & Details").setBold().setFontSize(10)));

                if (adminLogs.isEmpty()) adminTable.addCell(new Cell(1,3).add(new Paragraph("No Admin actions recorded.").setItalic().setFontSize(10)));
                for (AuditEntry entry : adminLogs) {
                    adminTable.addCell(new Cell().add(new Paragraph(entry.date).setFontSize(9)));
                    adminTable.addCell(new Cell().add(new Paragraph(entry.user).setFontSize(9)));
                    adminTable.addCell(new Cell().add(new Paragraph(entry.action + "\n" + entry.details).setFontSize(9)));
                }
                document.add(adminTable);

                // 🟦 MANAGER SECTION
                document.add(new Paragraph("👥 MANAGER ACTIVITY").setBold().setFontSize(14).setFontColor(BLUE).setBackgroundColor(new DeviceRgb(227, 242, 253)).setPadding(4f));
                Table managerTable = new Table(UnitValue.createPercentArray(new float[]{2, 2, 4})).useAllAvailableWidth();
                managerTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Date").setBold().setFontSize(10)));
                managerTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("User").setBold().setFontSize(10)));
                managerTable.addHeaderCell(new Cell().setBackgroundColor(GREY_BG).add(new Paragraph("Action & Details").setBold().setFontSize(10)));

                if (managerLogs.isEmpty()) managerTable.addCell(new Cell(1,3).add(new Paragraph("No Manager actions recorded.").setItalic().setFontSize(10)));
                for (AuditEntry entry : managerLogs) {
                    managerTable.addCell(new Cell().add(new Paragraph(entry.date).setFontSize(9)));
                    managerTable.addCell(new Cell().add(new Paragraph(entry.user).setFontSize(9)));
                    managerTable.addCell(new Cell().add(new Paragraph(entry.action + "\n" + entry.details).setFontSize(9)));
                }
                document.add(managerTable);
            }
            
            document.add(new Paragraph("\n[End of Official Audit Record]").setItalic().setFontSize(9).setTextAlignment(TextAlignment.CENTER).setFontColor(new DeviceRgb(150,150,150)));
            document.close(); shareFile(context, file, communityName + " - Security Audit");
        } catch (Exception e) {}
    }

    private static void shareFile(Context context, File file, String subject) {
        Uri uri = FileProvider.getUriForFile(context, context.getPackageName() + ".provider", file);
        Intent shareIntent = new Intent(Intent.ACTION_SEND); shareIntent.setType("application/pdf");
        shareIntent.putExtra(Intent.EXTRA_STREAM, uri); shareIntent.putExtra(Intent.EXTRA_SUBJECT, subject);
        shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        context.startActivity(Intent.createChooser(shareIntent, "Share PDF via..."));
    }
}
