package org.shda;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Environment;
import android.widget.Toast;
import androidx.core.content.FileProvider;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class PdfReportService {
    
    private static final DeviceRgb SAFFRON = new DeviceRgb(230, 81, 0);
    private static final DeviceRgb BLUE = new DeviceRgb(25, 118, 210);

    private static String getFormattedFileName(String communityName, String reportType) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmm", Locale.getDefault());
        String safeCommunity = communityName.replaceAll("[^a-zA-Z0-9]", "");
        String safeReport = reportType.replaceAll("[^a-zA-Z0-9]", "_");
        return safeCommunity + "_" + safeReport + "_" + sdf.format(new Date()) + ".pdf";
    }

    private static void addSanataniHeader(Context context, Document document, String communityName, String reportType) {
        document.add(new Paragraph(communityName.toUpperCase()).setFontColor(SAFFRON).setBold().setFontSize(24).setTextAlignment(TextAlignment.CENTER));
        document.add(new Paragraph(ShlokaEngine.getPdfSafeShloka(context)).setFontSize(11).setItalic().setFontColor(new DeviceRgb(117, 117, 117)).setTextAlignment(TextAlignment.CENTER));
        document.add(new Paragraph(reportType).setBold().setFontSize(14).setTextAlignment(TextAlignment.CENTER).setMarginTop(8f));
        document.add(new Paragraph("Generated: " + new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(new Date())).setFontSize(10).setItalic().setTextAlignment(TextAlignment.CENTER));
        document.add(new Paragraph("--------------------------------------------------\n").setTextAlignment(TextAlignment.CENTER));
    }

    // ✨ ELEGANT EVENT ITINERARY
    public static void generateEventItinerary(Context context, String communityName, EventActivity.Event event, String generatedBy) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Event_Itinerary"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL MANDIR EVENT ITINERARY");
            
            document.add(new Paragraph(event.title).setBold().setFontSize(18).setFontColor(SAFFRON).setTextAlignment(TextAlignment.CENTER));
            
            Table table = new Table(new float[]{1, 2});
            table.setWidth(UnitValue.createPercentValue(100)).setMarginTop(15f);
            
            table.addCell(new Cell().add(new Paragraph("Date & Time").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.dateStr + " at " + event.timeStr)));
            
            table.addCell(new Cell().add(new Paragraph("Location").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.location)));

            table.addCell(new Cell().add(new Paragraph("Description").setBold()));
            table.addCell(new Cell().add(new Paragraph(event.description)));

            if (event.adminComment != null && !event.adminComment.trim().isEmpty()) {
                table.addCell(new Cell().add(new Paragraph("Management Note").setBold()));
                table.addCell(new Cell().add(new Paragraph(event.adminComment).setItalic()));
            }

            table.addCell(new Cell().add(new Paragraph("Push Notifications Sent").setBold()));
            table.addCell(new Cell().add(new Paragraph(String.valueOf(event.notificationCount) + " alerts transmitted to members")));

            document.add(table);
            
            document.add(new Paragraph("\nEvent Scheduled By: " + event.createdBy).setItalic().setFontSize(10).setFontColor(new DeviceRgb(117, 117, 117)));
            document.add(new Paragraph("Document Generated By: " + generatedBy).setItalic().setFontSize(10).setFontColor(new DeviceRgb(117, 117, 117)));
            
            document.close(); shareFile(context, file, event.title + " Itinerary");
        } catch (Exception e) {}
    }

    // ✨ ELEGANT USER DASHBOARD PROFILE
    public static void generateMemberProfile(Context context, String communityName, Member member) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, member.id + "_Profile"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "OFFICIAL DEVOTEE RECORD");

            Table table = new Table(new float[]{1, 2});
            table.setWidth(UnitValue.createPercentValue(100)).setMarginTop(15f);

            table.addCell(new Cell().add(new Paragraph("Devotee Name").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.name)));

            table.addCell(new Cell().add(new Paragraph("SB-ID (System ID)").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.id).setFontColor(BLUE)));

            table.addCell(new Cell().add(new Paragraph("Phone Number").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.phone != null ? member.phone : "N/A")));

            table.addCell(new Cell().add(new Paragraph("Gotra").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.gotra != null ? member.gotra : "N/A")));

            table.addCell(new Cell().add(new Paragraph("Blood Group").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.bloodGroup != null ? member.bloodGroup : "N/A")));

            table.addCell(new Cell().add(new Paragraph("Address").setBold()));
            table.addCell(new Cell().add(new Paragraph(member.address != null ? member.address : "N/A")));

            table.addCell(new Cell().add(new Paragraph("Lifetime Donated").setBold().setFontColor(new DeviceRgb(46, 125, 50))));
            table.addCell(new Cell().add(new Paragraph("৳" + member.totalDonated).setBold().setFontColor(new DeviceRgb(46, 125, 50))));

            document.add(table);

            document.add(new Paragraph("\nData Verified By: " + (member.addedBySignature != null ? member.addedBySignature : "System")).setItalic().setFontSize(9));
            document.close(); shareFile(context, file, member.name + " Profile");
        } catch (Exception e) {}
    }

    public static class AuditEntry {
        public String date, user, action, details, role;
        public AuditEntry(String d, String u, String a, String det, String r) { date=d; user=u; action=a; details=det; role=r; }
    }

    // ✨ ELEGANT SECURITY AUDIT
    public static void generateBeautifulAuditReport(Context context, String communityName, List<AuditEntry> logs, String reportRange) {
        try {
            File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
            File file = new File(path, getFormattedFileName(communityName, "Security_Audit"));
            PdfWriter writer = new PdfWriter(file.getAbsolutePath()); Document document = new Document(new PdfDocument(writer));
            
            addSanataniHeader(context, document, communityName, "SECURITY AUDIT & ACTIVITY LOG");
            document.add(new Paragraph(reportRange).setFontSize(12).setTextAlignment(TextAlignment.CENTER).setMarginBottom(15f));
            
            if (logs.isEmpty()) { 
                document.add(new Paragraph("No activity recorded for this period.").setTextAlignment(TextAlignment.CENTER)); 
            } else {
                List<AuditEntry> adminLogs = new ArrayList<>(); List<AuditEntry> managerLogs = new ArrayList<>();
                for (AuditEntry log : logs) {
                    if ("ADMIN".equals(log.role)) adminLogs.add(log); else managerLogs.add(log);
                }

                // 🟥 SUPER ADMIN SECTION
                document.add(new Paragraph("🛡️ SUPER ADMIN ACTIVITY").setBold().setFontSize(14).setFontColor(SAFFRON).setBackgroundColor(new DeviceRgb(255, 243, 224)));
                Table adminTable = new Table(new float[]{1, 1, 3});
                adminTable.setWidth(UnitValue.createPercentValue(100)).setMarginBottom(15f);
                adminTable.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()));
                adminTable.addHeaderCell(new Cell().add(new Paragraph("User").setBold()));
                adminTable.addHeaderCell(new Cell().add(new Paragraph("Action & Details").setBold()));

                if (adminLogs.isEmpty()) adminTable.addCell(new Cell(1,3).add(new Paragraph("No Admin actions recorded.").setItalic()));
                for (AuditEntry entry : adminLogs) {
                    adminTable.addCell(new Cell().add(new Paragraph(entry.date).setFontSize(10)));
                    adminTable.addCell(new Cell().add(new Paragraph(entry.user).setFontSize(10)));
                    adminTable.addCell(new Cell().add(new Paragraph(entry.action + "\n" + entry.details).setFontSize(10)));
                }
                document.add(adminTable);

                // 🟦 MANAGER SECTION
                document.add(new Paragraph("👥 MANAGER ACTIVITY").setBold().setFontSize(14).setFontColor(BLUE).setBackgroundColor(new DeviceRgb(227, 242, 253)));
                Table managerTable = new Table(new float[]{1, 1, 3});
                managerTable.setWidth(UnitValue.createPercentValue(100));
                managerTable.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()));
                managerTable.addHeaderCell(new Cell().add(new Paragraph("User").setBold()));
                managerTable.addHeaderCell(new Cell().add(new Paragraph("Action & Details").setBold()));

                if (managerLogs.isEmpty()) managerTable.addCell(new Cell(1,3).add(new Paragraph("No Manager actions recorded.").setItalic()));
                for (AuditEntry entry : managerLogs) {
                    managerTable.addCell(new Cell().add(new Paragraph(entry.date).setFontSize(10)));
                    managerTable.addCell(new Cell().add(new Paragraph(entry.user).setFontSize(10)));
                    managerTable.addCell(new Cell().add(new Paragraph(entry.action + "\n" + entry.details).setFontSize(10)));
                }
                document.add(managerTable);
            }
            
            document.add(new Paragraph("\n[End of Official Audit Record]").setItalic().setFontSize(9).setTextAlignment(TextAlignment.CENTER).setFontColor(new DeviceRgb(150,150,150)));
            document.close(); shareFile(context, file, communityName + " - Security Audit");
        } catch (Exception e) {}
    }

    private static void shareFile(Context context, File file, String subject) {
        Uri uri = FileProvider.getUriForFile(context, context.getPackageName() + ".provider", file);
        Intent shareIntent = new Intent(Intent.ACTION_SEND); shareIntent.setType("application/pdf");
        shareIntent.putExtra(Intent.EXTRA_STREAM, uri); shareIntent.putExtra(Intent.EXTRA_SUBJECT, subject);
        shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        context.startActivity(Intent.createChooser(shareIntent, "Share PDF via..."));
    }

    // Keep your other legacy generation methods (Financial, Receipt, etc.) here so nothing breaks!
}
