package org.shda;

import android.content.Context;
import android.os.Environment;
import android.widget.Toast;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class PdfReportService {

    private static final DeviceRgb SAFFRON = new DeviceRgb(230, 81, 0);
    private static final DeviceRgb GREEN = new DeviceRgb(46, 125, 50);
    private static final DeviceRgb BLUE = new DeviceRgb(25, 118, 210);

    private static void sharePdf(Context context, File file) {
        try {
            android.net.Uri uri = androidx.core.content.FileProvider.getUriForFile(context, context.getPackageName() + ".provider", file);
            android.content.Intent intent = new android.content.Intent(android.content.Intent.ACTION_SEND);
            intent.setType("application/pdf");
            intent.putExtra(android.content.Intent.EXTRA_STREAM, uri);
            intent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
            context.startActivity(android.content.Intent.createChooser(intent, "Share PDF"));
        } catch (Exception e) {
            Toast.makeText(context, "PDF Saved to Documents! (View in File Manager)", Toast.LENGTH_LONG).show();
        }
    }

    private static File createBaseFile(Context context, String fileName) {
        File folder = new File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "SanataniReports");
        if (!folder.exists()) folder.mkdirs();
        return new File(folder, fileName + "_" + System.currentTimeMillis() + ".pdf");
    }

    private static void addSanataniHeader(Document document, String communityName, String reportTitle) {
        document.add(new Paragraph(communityName != null ? communityName.toUpperCase() : "SANATANI BANDHAN MANDIR")
                .setTextAlignment(TextAlignment.CENTER).setFontSize(22).setBold().setFontColor(SAFFRON));
        document.add(new Paragraph("\"Ahimsa paramo dharma\" (Non-violence is the highest religion) - Mahabharata")
                .setTextAlignment(TextAlignment.CENTER).setFontSize(10).setItalic().setFontColor(ColorConstants.GRAY));
        document.add(new Paragraph(reportTitle.toUpperCase())
                .setTextAlignment(TextAlignment.CENTER).setFontSize(14).setBold().setBackgroundColor(ColorConstants.LIGHT_GRAY).setMarginTop(10));
        document.add(new Paragraph("Generated: " + new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(new Date()))
                .setTextAlignment(TextAlignment.CENTER).setFontSize(10).setItalic().setMarginBottom(15));
    }

    // ✨ NEW: The Prestige Watermark Engine ✨
    private static void addSanataniFooter(Context context, Document document) {
        SessionManager session = new SessionManager(context);
        String footerText;
        
        if ("PREMIUM".equalsIgnoreCase(session.getPlan())) {
            footerText = "\nAuthorized & Generated via Sanatani Bandhan SAMRAT PRO";
        } else {
            footerText = "\nGenerated by Sanatani Bandhan (Free Version) - Upgrade to Pro for unlimited exports.";
        }
        
        document.add(new Paragraph(footerText)
                .setTextAlignment(TextAlignment.RIGHT).setFontSize(9).setItalic().setFontColor(ColorConstants.GRAY));
    }

    private static void addThankYouMessage(Document document, String communityName) {
        String orgName = communityName != null ? communityName : "our community";
        document.add(new Paragraph("\n🙏 Namaskar!\n\nThank you for your generous contribution to " + orgName + ". Your selfless support ensures our prosperity and the continued preservation of our Dharma. May the blessings of the divine always be with you and your family.\n\n\"Dharmo Rakshati Rakshitah\" (Dharma protects those who protect it).")
                .setTextAlignment(TextAlignment.CENTER).setFontSize(12).setItalic().setFontColor(SAFFRON).setMarginTop(20));
    }

    public static void generateComparisonReport(Context context, String communityName, List<TransactionActivity.SingleDonation> donations, List<ExpenseActivity.Expense> expenses, long startTs, long endTs, float totalIncome, float totalExpense) {
        try {
            File file = createBaseFile(context, "Income_Vs_Expense_Report");
            Document document = new Document(new PdfDocument(new PdfWriter(new FileOutputStream(file))), PageSize.A4);
            SimpleDateFormat titleSdf = new SimpleDateFormat("dd MMM yyyy", Locale.getDefault());
            String dateRange = titleSdf.format(new Date(startTs)) + " to " + titleSdf.format(new Date(endTs));
            addSanataniHeader(document, communityName, "Income vs Expense Comparison\n(" + dateRange + ")");

            document.add(new Paragraph("DONATIONS (INCOME)").setBold().setFontSize(14).setFontColor(GREEN).setMarginTop(10));
            Table incTable = new Table(new float[]{2, 4, 2}); incTable.setWidth(UnitValue.createPercentValue(100));
            incTable.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            incTable.addHeaderCell(new Cell().add(new Paragraph("Donor / Source").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            incTable.addHeaderCell(new Cell().add(new Paragraph("Amount").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            for(TransactionActivity.SingleDonation d : donations) {
                incTable.addCell(new Paragraph(titleSdf.format(new Date(d.timestamp))));
                incTable.addCell(new Paragraph(d.name));
                incTable.addCell(new Paragraph("BDT " + d.amount));
            }
            document.add(incTable);
            document.add(new Paragraph("Total Income: BDT " + totalIncome).setBold().setTextAlignment(TextAlignment.RIGHT).setFontColor(GREEN).setMarginBottom(15));

            document.add(new Paragraph("EXPENSES").setBold().setFontSize(14).setFontColor(ColorConstants.RED));
            Table expTable = new Table(new float[]{2, 4, 2}); expTable.setWidth(UnitValue.createPercentValue(100));
            expTable.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            expTable.addHeaderCell(new Cell().add(new Paragraph("Event / Item").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            expTable.addHeaderCell(new Cell().add(new Paragraph("Cost").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            for(ExpenseActivity.Expense e : expenses) {
                expTable.addCell(new Paragraph(titleSdf.format(new Date(e.timestamp))));
                expTable.addCell(new Paragraph(e.eventName + " - " + e.itemName));
                expTable.addCell(new Paragraph("BDT " + e.amount));
            }
            document.add(expTable);
            document.add(new Paragraph("Total Expense: BDT " + totalExpense).setBold().setTextAlignment(TextAlignment.RIGHT).setFontColor(ColorConstants.RED).setMarginBottom(15));

            float net = totalIncome - totalExpense;
            com.itextpdf.kernel.colors.Color netColor = net >= 0 ? GREEN : ColorConstants.RED;
            document.add(new Paragraph("\nNET BALANCE FOR PERIOD: BDT " + net).setBold().setFontSize(16).setTextAlignment(TextAlignment.RIGHT).setFontColor(netColor).setMarginTop(10));

            addSanataniFooter(context, document); 
            document.close();
            sharePdf(context, file); 
        } catch (Exception e) {}
    }

    public static void generateMemberDirectory(Context context, String communityName, List<MemberAdapter.Member> members) {
        try {
            File file = createBaseFile(context, "Member_Directory");
            Document document = new Document(new PdfDocument(new PdfWriter(new FileOutputStream(file))), PageSize.A4);
            addSanataniHeader(document, communityName, "Official Devotee Directory");
            Table table = new Table(new float[]{3, 3, 3}); table.setWidth(UnitValue.createPercentValue(100));
            table.addHeaderCell(new Cell().add(new Paragraph("Name").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Phone").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Gotra").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            for (MemberAdapter.Member m : members) {
                table.addCell(new Paragraph(m.name)); 
                table.addCell(new Paragraph(m.phone != null ? m.phone : ""));
                table.addCell(new Paragraph(m.gotra != null ? m.gotra : "")); 
            }
            document.add(table); 
            addSanataniFooter(context, document); 
            document.close();
            sharePdf(context, file); 
        } catch (Exception e) { Toast.makeText(context, "Error: " + e.getMessage(), Toast.LENGTH_SHORT).show(); }
    }

    public static void generateFinancialReport(Context context, String communityName, List<String> dates, List<String> names, List<Float> amounts, List<String> notes, float totalCollected, String title) {
        try {
            File file = createBaseFile(context, "Master_Donation_Ledger");
            Document document = new Document(new PdfDocument(new PdfWriter(new FileOutputStream(file))), PageSize.A4);
            addSanataniHeader(document, communityName, title);
            Table table = new Table(new float[]{2, 3, 2, 3}); table.setWidth(UnitValue.createPercentValue(100));
            table.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Donor Name").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Amount").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Note / Purpose").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            for (int i = 0; i < names.size(); i++) {
                table.addCell(new Paragraph(dates.get(i))); table.addCell(new Paragraph(names.get(i)));
                table.addCell(new Paragraph("BDT " + amounts.get(i)).setFontColor(GREEN)); table.addCell(new Paragraph(notes.get(i)));
            }
            document.add(table); document.add(new Paragraph("\nTotal Donation in this Report: BDT " + totalCollected).setBold().setFontSize(14).setFontColor(GREEN).setTextAlignment(TextAlignment.RIGHT));
            addSanataniFooter(context, document); 
            document.close();
            sharePdf(context, file); 
        } catch (Exception e) {}
    }

    public static void generateExpenseReport(Context context, String communityName, List<ExpenseActivity.Expense> expenses, float totalSpent, String title) {
        try {
            File file = createBaseFile(context, "Master_Utsav_Expense");
            Document document = new Document(new PdfDocument(new PdfWriter(new FileOutputStream(file))), PageSize.A4);
            addSanataniHeader(document, communityName, title);
            Table table = new Table(new float[]{2, 3, 2, 2}); table.setWidth(UnitValue.createPercentValue(100));
            table.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Event & Item").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Cost").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Handled By").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy", Locale.getDefault());
            for (ExpenseActivity.Expense e : expenses) {
                table.addCell(new Paragraph(sdf.format(new Date(e.timestamp))));
                table.addCell(new Paragraph(e.eventName + " - " + e.itemName));
                table.addCell(new Paragraph("BDT " + e.amount).setFontColor(ColorConstants.RED));
                table.addCell(new Paragraph(e.involvedPerson));
            }
            document.add(table); document.add(new Paragraph("\nTotal Expenses in this Report: BDT " + totalSpent).setBold().setFontSize(14).setFontColor(ColorConstants.RED).setTextAlignment(TextAlignment.RIGHT));
            addSanataniFooter(context, document); 
            document.close();
            sharePdf(context, file); 
        } catch (Exception e) {}
    }

    public static void generateSecurityAudit(Context context, String communityName, List<DashboardActivity.AuditLog> logs, String title) {
        try {
            File file = createBaseFile(context, "Security_Audit_Report");
            Document document = new Document(new PdfDocument(new PdfWriter(new FileOutputStream(file))), PageSize.A4);
            addSanataniHeader(document, communityName, title);

            Table table = new Table(new float[]{2, 2, 2, 4}); 
            table.setWidth(UnitValue.createPercentValue(100));
            table.addHeaderCell(new Cell().add(new Paragraph("Date").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("User/Manager").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Action").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            table.addHeaderCell(new Cell().add(new Paragraph("Description").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));

            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault());
            for (DashboardActivity.AuditLog log : logs) {
                table.addCell(new Paragraph(sdf.format(new Date(log.timestamp))).setFontSize(9));
                table.addCell(new Paragraph(log.managerName != null ? log.managerName : "System").setFontSize(9));
                table.addCell(new Paragraph(log.actionType != null ? log.actionType : "").setFontColor(ColorConstants.RED).setBold().setFontSize(9));
                table.addCell(new Paragraph(log.description != null ? log.description : "").setFontSize(9));
            }

            document.add(table);
            document.add(new Paragraph("\nTotal Audit Records: " + logs.size()).setItalic().setTextAlignment(TextAlignment.RIGHT));

            addSanataniFooter(context, document); 
            document.close();
            sharePdf(context, file); 
        } catch (Exception e) {
            Toast.makeText(context, "Error generating Audit PDF.", Toast.LENGTH_SHORT).show();
        }
    }
}
